WITH bruto AS (
  SELECT 'google-ads-cwt3' _fonte,SAFE_CAST(c.id AS INT64) id_campanha,REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/') id_conta,NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),'') campanha,SAFE_CAST(c.status AS STRING) status,SAFE_CAST(c.serving_status AS STRING) status_veiculacao,SAFE_CAST(c.primary_status AS STRING) status_primario,SAFE_CAST(c.advertising_channel_type AS STRING) canal,SAFE_CAST(c.advertising_channel_sub_type AS STRING) subcanal,SAFE_CAST(c.bidding_strategy_type AS STRING) estrategia_lance,SAFE_CAST(c.bidding_strategy_system_status AS STRING) status_estrategia,SAFE_CAST(c.start_date AS DATE) data_inicio,SAFE_CAST(c.end_date AS DATE) data_fim,SAFE_CAST(c.optimization_score AS FLOAT64) score_otimizacao,SAFE_CAST(c.experiment_type AS STRING) tipo_experimento FROM `vanguardamartech_acesso_saude_google_ads`.`google_ads_acesso_saudecampaigns` c
  UNION ALL
  SELECT 'google-ads-DzVL',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_ola_casa_nova_g_ads`.`google_ads_ola_casa_novacampaigns` c
  UNION ALL
  SELECT 'google-ads-vfUV',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_move_rental_cars_g_ads`.`google_ads_move_rentalcampaigns` c
  UNION ALL
  SELECT 'google-ads-QuKh',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_don_watches_conta_1_g_ads`.`google_ads_don_watches_2campaigns` c
  UNION ALL
  SELECT 'google-ads-vE2C',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_don_watches_conta_2`.`google_ads_watches_2campaigns` c
  UNION ALL
  SELECT 'google-ads-PmFB',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_braga_varejo`.`google_ads_braga_varejocampaigns` c
  UNION ALL
  SELECT 'google-ads-5J1y',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_braga_yamaha_consorcios_2`.`google_ads_yamaha_2campaigns` c
  UNION ALL
  SELECT 'google-ads-Pk69',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_braga_yamaha_consorcios`.`google_ads_braga_yamaha_consorccampaigns` c
  UNION ALL
  SELECT 'google-ads-SyTu',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_royal_enfield`.`google_ads_royal_enfieldcampaigns` c
  UNION ALL
  SELECT 'google-ads-6Z2v',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_braga_acessorios`.`google_ads_braga_acessorioscampaigns` c
  UNION ALL
  SELECT 'google-ads-PsES',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_braga_veiculos`.`google_ads_pos_vendascampaigns` c
  UNION ALL
  SELECT 'google-ads-RCRU',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_braga_motors_mini`.`google_ads_braga_minicampaigns` c
  UNION ALL
  SELECT 'google-ads-VozJ',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_braga_motorrad`.`google_ads_braga_motorradcampaigns` c
  UNION ALL
  SELECT 'google-ads-cFrH',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_braga_motors_bmw_g_ads`.`google_ads_braga_bmwcampaigns` c
  UNION ALL
  SELECT 'google-ads-URNQ',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_dmelo`.`google_ads_dmelocampaigns` c
  UNION ALL
  SELECT 'google-ads-mEnk',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_caa`.`google_ads_caa_tintascampaigns` c
  UNION ALL
  SELECT 'google-ads-A1kM',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_caa_aluminio`.`google_ads_caa_aluminiocampaigns` c
  UNION ALL
  SELECT 'google-ads-rYKp',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_rodrix_g_ads`.`google_ads_rodrix_motoscampaigns` c
  UNION ALL
  SELECT 'google-ads-C4Aq',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_deb_transportadora_g_ads`.`google_ads_deb_transportadoracampaigns` c
  UNION ALL
  SELECT 'google-ads-PnyV',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_rei_das_mangueiras_g_ads`.`google_ads_rei_das_mangueirascampaigns` c
  UNION ALL
  SELECT 'google-ads-0B2k',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_pneu_forte_distribuidora`.`google_ads_pneu_forte_distcampaigns` c
  UNION ALL
  SELECT 'google-ads-GZ55',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_millenium_g_ads`.`google_ads_milleniumcampaigns` c
  UNION ALL
  SELECT 'google-ads-802k',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_pneu_express`.`google_ads_pneu_expresscampaigns` c
  UNION ALL
  SELECT 'google-ads-Jl1R',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_smile_pneus`.`google_ads_smile_pneuscampaigns` c
  UNION ALL
  SELECT 'google-ads-x20o',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_steel_port_g_ads`.`google_ads_steel_portcampaigns` c
  UNION ALL
  SELECT 'google-ads-ZcMG',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_amz_geradores_g_ads`.`google_ads_amz_geradorescampaigns` c
  UNION ALL
  SELECT 'google-ads-wypN',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_dr_cabral_conta_1`.`google_ads_dr_cabral_1campaigns` c
  UNION ALL
  SELECT 'google-ads-AMd2',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_santo_remedio_g_ads`.`google_ads_santo_remediocampaigns` c
  UNION ALL
  SELECT 'google-ads-rSav',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_hospital_santa_julia_g_ads`.`google_ads_h_santa_juliacampaigns` c
  UNION ALL
  SELECT 'google-ads-jT4J',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_constroi_incorporadora_g_ads`.`google_ads_constroicampaigns` c
  UNION ALL
  SELECT 'google-ads-ABUl',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_doctor_mais_g_ads`.`google_ads_doctor_maiscampaigns` c
  UNION ALL
  SELECT 'google-ads-R4be',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_colmeia`.`google_ads_colmeiacampaigns` c
  UNION ALL
  SELECT 'google-ads-fwxw',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_amazoncopy_g_ads`.`google_ads_amazoncopycampaigns` c
  UNION ALL
  SELECT 'google-ads-dMx7',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_bigazine_g_ads`.`google_ads_bigazinecampaigns` c
  UNION ALL
  SELECT 'google-ads-x36N',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_arena_tintas_g_ads`.`google_ads_arena_tintascampaigns` c
  UNION ALL
  SELECT 'google-ads-WxA8',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_ba_eletrica_g_ads`.`google_ads_ba_eletricacampaigns` c
  UNION ALL
  SELECT 'google-ads-Llsu',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_pmz_grupo_ecomm`.`google_ads_pmz_ecommcampaigns` c
  UNION ALL
  SELECT 'google-ads-NP4k',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_pmz_loja`.`google_pmz_grupo_lojacampaigns` c
  UNION ALL
  SELECT 'google-ads-PdSr',SAFE_CAST(c.id AS INT64),REGEXP_EXTRACT(c.resource_name, r'customers/([0-9]+)/'),NULLIF(TRIM(SAFE_CAST(c.name AS STRING)),''),SAFE_CAST(c.status AS STRING),SAFE_CAST(c.serving_status AS STRING),SAFE_CAST(c.primary_status AS STRING),SAFE_CAST(c.advertising_channel_type AS STRING),SAFE_CAST(c.advertising_channel_sub_type AS STRING),SAFE_CAST(c.bidding_strategy_type AS STRING),SAFE_CAST(c.bidding_strategy_system_status AS STRING),SAFE_CAST(c.start_date AS DATE),SAFE_CAST(c.end_date AS DATE),SAFE_CAST(c.optimization_score AS FLOAT64),SAFE_CAST(c.experiment_type AS STRING) FROM `vanguardamartech_pmz_escola_de_mecanicos`.`google_ads_pmz_escola_mecanicoscampaigns` c
),
orcamento AS (
  SELECT 'google-ads-cwt3' fonte,SAFE_CAST(o.campaign_id AS INT64) id_campanha,ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)) orc_diario_micros,ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)) orc_total_micros,ANY_VALUE(SAFE_CAST(o.period AS STRING)) periodo,ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)) metodo_entrega,ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) compartilhado FROM `vanguardamartech_acesso_saude_google_ads`.`google_ads_acesso_saudecampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-DzVL',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_ola_casa_nova_g_ads`.`google_ads_ola_casa_novacampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-vfUV',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_move_rental_cars_g_ads`.`google_ads_move_rentalcampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-QuKh',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_don_watches_conta_1_g_ads`.`google_ads_don_watches_2campaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-vE2C',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_don_watches_conta_2`.`google_ads_watches_2campaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-PmFB',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_braga_varejo`.`google_ads_braga_varejocampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-5J1y',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_braga_yamaha_consorcios_2`.`google_ads_yamaha_2campaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-Pk69',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_braga_yamaha_consorcios`.`google_ads_braga_yamaha_consorccampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-SyTu',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_royal_enfield`.`google_ads_royal_enfieldcampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-6Z2v',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_braga_acessorios`.`google_ads_braga_acessorioscampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-PsES',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_braga_veiculos`.`google_ads_pos_vendascampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-RCRU',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_braga_motors_mini`.`google_ads_braga_minicampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-VozJ',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_braga_motorrad`.`google_ads_braga_motorradcampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-cFrH',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_braga_motors_bmw_g_ads`.`google_ads_braga_bmwcampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-URNQ',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_dmelo`.`google_ads_dmelocampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-mEnk',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_caa`.`google_ads_caa_tintascampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-A1kM',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_caa_aluminio`.`google_ads_caa_aluminiocampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-rYKp',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_rodrix_g_ads`.`google_ads_rodrix_motoscampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-C4Aq',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_deb_transportadora_g_ads`.`google_ads_deb_transportadoracampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-PnyV',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_rei_das_mangueiras_g_ads`.`google_ads_rei_das_mangueirascampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-0B2k',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_pneu_forte_distribuidora`.`google_ads_pneu_forte_distcampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-GZ55',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_millenium_g_ads`.`google_ads_milleniumcampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-802k',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_pneu_express`.`google_ads_pneu_expresscampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-Jl1R',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_smile_pneus`.`google_ads_smile_pneuscampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-x20o',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_steel_port_g_ads`.`google_ads_steel_portcampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-ZcMG',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_amz_geradores_g_ads`.`google_ads_amz_geradorescampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-wypN',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_dr_cabral_conta_1`.`google_ads_dr_cabral_1campaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-AMd2',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_santo_remedio_g_ads`.`google_ads_santo_remediocampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-rSav',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_hospital_santa_julia_g_ads`.`google_ads_h_santa_juliacampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-jT4J',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_constroi_incorporadora_g_ads`.`google_ads_constroicampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-ABUl',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_doctor_mais_g_ads`.`google_ads_doctor_maiscampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-R4be',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_colmeia`.`google_ads_colmeiacampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-fwxw',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_amazoncopy_g_ads`.`google_ads_amazoncopycampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-dMx7',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_bigazine_g_ads`.`google_ads_bigazinecampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-x36N',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_arena_tintas_g_ads`.`google_ads_arena_tintascampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-WxA8',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_ba_eletrica_g_ads`.`google_ads_ba_eletricacampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-Llsu',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_pmz_grupo_ecomm`.`google_ads_pmz_ecommcampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-NP4k',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_pmz_loja`.`google_pmz_grupo_lojacampaign_budget` o GROUP BY 1,2
  UNION ALL
  SELECT 'google-ads-PdSr',SAFE_CAST(o.campaign_id AS INT64),ANY_VALUE(SAFE_CAST(o.amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.total_amount_micros AS INT64)),ANY_VALUE(SAFE_CAST(o.period AS STRING)),ANY_VALUE(SAFE_CAST(o.delivery_method AS STRING)),ANY_VALUE(SAFE_CAST(o.explicitly_shared AS BOOL)) FROM `vanguardamartech_pmz_escola_de_mecanicos`.`google_ads_pmz_escola_mecanicoscampaign_budget` o GROUP BY 1,2
),
base AS (
  SELECT
    b.*,
    TO_HEX(MD5(TO_JSON_STRING(b)))                            AS _payload_hash
  FROM bruto b
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY b._fonte, b.id_campanha ORDER BY b.campanha) = 1
)
SELECT
  b.id_campanha,
  b.id_conta,
  -- cliente e moeda vem da dimensao trs_google_ads__conta, resolvidos por id_conta
  -- (extraido do resource_name). Eram literais escritos a mao, um par por fonte:
  -- 39 no total nesta query. Agora ha uma fonte de verdade so, semeada do MCC.
  d.cliente,
  d.moeda,
  b.campanha,

  b.status,
  b.status_veiculacao,
  b.status_primario,
  (b.status = 'ENABLED')                                      AS ativa,

  b.canal,
  b.subcanal,
  b.estrategia_lance,
  b.status_estrategia,

  b.data_inicio,
  IF(b.data_fim >= DATE '2037-01-01', NULL, b.data_fim)       AS data_fim,
  (b.data_fim >= DATE '2037-01-01')                           AS sem_fim_definido,

  orc.orc_diario_micros                                       AS orcamento_diario_micros,
  SAFE_DIVIDE(orc.orc_diario_micros, 1000000)                 AS orcamento_diario,
  orc.orc_total_micros                                        AS orcamento_total_micros,
  SAFE_DIVIDE(orc.orc_total_micros, 1000000)                  AS orcamento_total,
  orc.periodo                                                 AS periodo_orcamento,
  orc.metodo_entrega                                          AS metodo_entrega_orcamento,
  orc.compartilhado                                           AS orcamento_compartilhado,

  b.score_otimizacao,
  b.tipo_experimento,

  -- Se a dimensao nao tiver a conta, cliente e moeda vem NULL. A flag existe para
  -- que isso apareca em vez de sumir dentro de um GROUP BY.
  (d.id_conta IS NULL)                                        AS flag_conta_nao_catalogada,

  CURRENT_TIMESTAMP()                                         AS _extraido_at,
  b._fonte,
  b._payload_hash
FROM base b
LEFT JOIN orcamento orc
  ON orc.id_campanha = b.id_campanha AND orc.fonte = b._fonte
-- LEFT e proposital: INNER descartaria campanha em silencio se a dimensao
-- estivesse desatualizada. Aqui a linha fica e a flag acende.
LEFT JOIN `vanguardamartech_trusted`.`trs_google_ads__conta` d
  ON d.id_conta = b.id_conta
