-- trs_vjob__config_cliente (query-IJEg) · Trusted / VJOB · L2 INTERNAL. Grao: uma configuracao recorrente por conta de atendimento. Chave: (origem, id_origem).
-- Origem: mysql-yIOn, tbcheckin_semanal_config, tbcheckin_social_media_config, tbescopo_distribuicao_config, tbchecklistclientes, rotinas_cadastros, avaliacaocs_clientes.
-- Gatilho: evento em query-MZdN. Cliente = CONTA DE ATENDIMENTO (tbclientesatedimentos), medido 100% nas seis. Zero em criado_por/atualizado_por e sentinela.
-- Link de documento e observacao nao sao emitidos, so a presenca. Datas: hora local, sem conversao.
WITH base AS (
SELECT 'CHECKIN_SEMANAL' AS origem, CAST(id AS INT64) AS id_origem, CAST(id_cliente AS INT64) AS id_conta_atendimento, CAST(NULL AS INT64) AS id_servico, CAST(NULL AS INT64) AS id_setor, CAST(NULL AS INT64) AS id_responsavel, CAST(NULL AS INT64) AS id_item, CAST(NULL AS STRING) AS titulo, CAST(dia_semana AS INT64) AS dia_semana, CAST(NULL AS INT64) AS dia_mes, CAST(NULL AS INT64) AS dia_util_numero, CAST(NULL AS INT64) AS antecedencia_dias, CAST(NULL AS STRING) AS frequencia, CAST(NULL AS INT64) AS quantidade_dia, CAST(NULL AS STRING) AS tipo_dias, CAST(NULL AS BOOL) AS excluir_feriados, CAST(NULL AS DATE) AS data_inicio, CAST(NULL AS DATE) AS data_fim, CAST(NULL AS BOOL) AS feito, CAST(NULL AS BOOL) AS obrigatorio, CAST(NULL AS BOOL) AS gera_automaticamente, CAST(NULL AS STRING) AS prioridade, CAST(ativo AS INT64)=1 AS ativo, CAST(NULL AS BOOL) AS tem_link_documento, NULLIF(CAST(criado_por AS INT64),0) AS id_criado_por, NULLIF(CAST(atualizado_por AS INT64),0) AS id_atualizado_por, CAST(criado_em AS TIMESTAMP) AS criado_em, CAST(atualizado_em AS TIMESTAMP) AS atualizado_em FROM `vanguardamartech_vjob_real_mysql`.`mysql_vjobvjob_2024_tbcheckin_semanal_config`
UNION ALL SELECT 'CHECKIN_SOCIAL', CAST(id AS INT64), CAST(id_cliente AS INT64), NULL, NULL, CAST(id_responsavel AS INT64), NULL, NULL, CAST(dia_semana AS INT64), NULL, NULL, NULL, NULLIF(TRIM(frequencia),''), NULL, NULL, NULL, CAST(data_inicio AS DATE), NULL, NULL, NULL, NULL, NULL, CAST(ativo AS INT64)=1, NULLIF(TRIM(link_documento),'') IS NOT NULL, NULLIF(CAST(criado_por AS INT64),0), NULLIF(CAST(atualizado_por AS INT64),0), CAST(criado_em AS TIMESTAMP), CAST(atualizado_em AS TIMESTAMP) FROM `vanguardamartech_vjob_real_mysql`.`mysql_vjobvjob_2024_tbcheckin_social_media_config`
UNION ALL SELECT 'DISTRIBUICAO_ESCOPO', CAST(id AS INT64), CAST(id_cliente AS INT64), CAST(id_servico AS INT64), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(quantidade_dia AS INT64), NULLIF(TRIM(tipo_dias),''), CAST(excluir_feriados AS INT64)=1, NULL, NULL, NULL, NULL, NULL, NULL, CAST(ativo AS INT64)=1, NULL, NULLIF(CAST(criado_por AS INT64),0), NULLIF(CAST(atualizado_por AS INT64),0), CAST(criado_em AS TIMESTAMP), CAST(atualizado_em AS TIMESTAMP) FROM `vanguardamartech_vjob_real_mysql`.`mysql_vjobvjob_2024_tbescopo_distribuicao_config`
UNION ALL SELECT 'CHECKLIST_CLIENTE', CAST(id AS INT64), CAST(id_cliente AS INT64), NULL, NULL, NULL, CAST(id_checklist AS INT64), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(`data` AS DATE), NULL, CAST(feito AS INT64)=1, CAST(obrigatorio AS INT64)=1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM `vanguardamartech_vjob_real_mysql`.`mysql_vjobvjob_2024_tbchecklistclientes`
UNION ALL SELECT 'ROTINA', CAST(id AS INT64), CAST(cliente_id AS INT64), NULL, CAST(setor_id AS INT64), CAST(responsavel_padrao_id AS INT64), CAST(tipo_prazo_id AS INT64), NULLIF(TRIM(titulo),''), CAST(dia_semana AS INT64), CAST(dia_mes AS INT64), CAST(dia_util_numero AS INT64), CAST(antecedencia_dias AS INT64), NULL, NULL, NULL, NULL, CAST(vigencia_inicio AS DATE), CAST(vigencia_fim AS DATE), NULL, NULL, CAST(gera_automaticamente AS INT64)=1, NULLIF(TRIM(prioridade),''), CAST(ativa AS INT64)=1, NULL, NULLIF(CAST(criado_por AS INT64),0), NULLIF(CAST(atualizado_por AS INT64),0), CAST(criado_em AS TIMESTAMP), CAST(atualizado_em AS TIMESTAMP) FROM `vanguardamartech_vjob_real_mysql`.`mysql_vjobvjob_2024_rotinas_cadastros`
UNION ALL SELECT 'AVALIACAO_CS', CAST(cliente_id AS INT64), CAST(cliente_id AS INT64), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULLIF(CAST(atualizado_por AS INT64),0), NULL, CAST(atualizado_em AS TIMESTAMP) FROM `vanguardamartech_vjob_real_mysql`.`mysql_vjobvjob_2024_avaliacaocs_clientes`
),
tratado AS (
  SELECT b.*,
    (a.id IS NULL) AS flag_conta_nao_catalogada,
    (b.dia_semana IS NOT NULL AND b.dia_semana NOT BETWEEN 1 AND 7) AS flag_dia_semana_fora_de_1_a_7
  FROM base b LEFT JOIN `vanguardamartech_vjob_real_mysql`.`mysql_vjobvjob_2024_tbclientesatedimentos` a ON a.id = b.id_conta_atendimento
)
SELECT t.*, CURRENT_TIMESTAMP() AS _extraido_at, 'mysql-yIOn' AS _fonte, 'America/Sao_Paulo' AS _fuso,
  TO_HEX(MD5(TO_JSON_STRING(t))) AS _payload_hash
FROM tratado t
