-- trs_google_ads__termo_busca
-- Trusted de segmentacao do Google Ads, consolidada nas 39 fontes.
-- Grao: id_campanha, id_grupo_anuncio, termo, tipo_correspondencia, data.
-- Origem: search_term_performance em cada camada de fonte.
--
-- AS TABELAS DE BREAKDOWN NAO TEM IDENTIFICADOR DE CONTA. Nem account_id nem
-- resource_name. O id_conta e injetado por ramo, do mapeamento fonte -> customer_id
-- validado contra a API do Google Ads em 27/08/2026. Se uma fonte for repontada
-- para outra conta, este literal passa a mentir -- reconferir ao mexer em fonte.
WITH uniao AS (
  SELECT
    'google-ads-cwt3' AS _fonte,
    '1752443056' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_acesso_saude_google_ads`.`google_ads_acesso_saudesearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-DzVL' AS _fonte,
    '6155043001' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_ola_casa_nova_g_ads`.`google_ads_ola_casa_novasearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-vfUV' AS _fonte,
    '5685989711' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_move_rental_cars_g_ads`.`google_ads_move_rentalsearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-QuKh' AS _fonte,
    '9451726644' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_don_watches_conta_1_g_ads`.`google_ads_don_watches_2search_term_performance` x
  UNION ALL
  SELECT
    'google-ads-vE2C' AS _fonte,
    '8553733895' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_don_watches_conta_2`.`google_ads_watches_2search_term_performance` x
  UNION ALL
  SELECT
    'google-ads-PmFB' AS _fonte,
    '8437632791' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_braga_varejo`.`google_ads_braga_varejosearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-5J1y' AS _fonte,
    '4216086233' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_braga_yamaha_consorcios_2`.`google_ads_yamaha_2search_term_performance` x
  UNION ALL
  SELECT
    'google-ads-Pk69' AS _fonte,
    '1874995593' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_braga_yamaha_consorcios`.`google_ads_braga_yamaha_consorcsearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-SyTu' AS _fonte,
    '1214474505' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_royal_enfield`.`google_ads_royal_enfieldsearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-6Z2v' AS _fonte,
    '3193747131' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_braga_acessorios`.`google_ads_braga_acessoriossearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-PsES' AS _fonte,
    '1807325368' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_braga_veiculos`.`google_ads_pos_vendassearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-RCRU' AS _fonte,
    '8766638384' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_braga_motors_mini`.`google_ads_braga_minisearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-VozJ' AS _fonte,
    '6604892813' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_braga_motorrad`.`google_ads_braga_motorradsearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-cFrH' AS _fonte,
    '9359858042' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_braga_motors_bmw_g_ads`.`google_ads_braga_bmwsearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-URNQ' AS _fonte,
    '3310579239' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_dmelo`.`google_ads_dmelosearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-mEnk' AS _fonte,
    '8837950560' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_caa`.`google_ads_caa_tintassearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-A1kM' AS _fonte,
    '9382044362' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_caa_aluminio`.`google_ads_caa_aluminiosearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-rYKp' AS _fonte,
    '9739407801' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_rodrix_g_ads`.`google_ads_rodrix_motossearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-C4Aq' AS _fonte,
    '4032355891' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_deb_transportadora_g_ads`.`google_ads_deb_transportadorasearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-PnyV' AS _fonte,
    '9580379854' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_rei_das_mangueiras_g_ads`.`google_ads_rei_das_mangueirassearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-0B2k' AS _fonte,
    '6666958748' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_pneu_forte_distribuidora`.`google_ads_pneu_forte_distsearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-GZ55' AS _fonte,
    '8904126755' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_millenium_g_ads`.`google_ads_milleniumsearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-802k' AS _fonte,
    '5921711317' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_pneu_express`.`google_ads_pneu_expresssearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-Jl1R' AS _fonte,
    '1395906460' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_smile_pneus`.`google_ads_smile_pneussearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-x20o' AS _fonte,
    '9870901843' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_steel_port_g_ads`.`google_ads_steel_portsearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-ZcMG' AS _fonte,
    '3397886954' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_amz_geradores_g_ads`.`google_ads_amz_geradoressearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-wypN' AS _fonte,
    '7381920209' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_dr_cabral_conta_1`.`google_ads_dr_cabral_1search_term_performance` x
  UNION ALL
  SELECT
    'google-ads-AMd2' AS _fonte,
    '2819044460' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_santo_remedio_g_ads`.`google_ads_santo_remediosearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-rSav' AS _fonte,
    '2871944411' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_hospital_santa_julia_g_ads`.`google_ads_h_santa_juliasearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-jT4J' AS _fonte,
    '2404777291' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_constroi_incorporadora_g_ads`.`google_ads_constroisearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-ABUl' AS _fonte,
    '6167711319' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_doctor_mais_g_ads`.`google_ads_doctor_maissearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-R4be' AS _fonte,
    '7494330271' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_colmeia`.`google_ads_colmeiasearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-fwxw' AS _fonte,
    '8887022182' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_amazoncopy_g_ads`.`google_ads_amazoncopysearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-dMx7' AS _fonte,
    '2494093513' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_bigazine_g_ads`.`google_ads_bigazinesearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-x36N' AS _fonte,
    '3152479850' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_arena_tintas_g_ads`.`google_ads_arena_tintassearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-WxA8' AS _fonte,
    '3746529772' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_ba_eletrica_g_ads`.`google_ads_ba_eletricasearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-Llsu' AS _fonte,
    '5210673200' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_pmz_grupo_ecomm`.`google_ads_pmz_ecommsearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-NP4k' AS _fonte,
    '8740065197' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_pmz_loja`.`google_pmz_grupo_lojasearch_term_performance` x
  UNION ALL
  SELECT
    'google-ads-PdSr' AS _fonte,
    '7280103768' AS id_conta,
    CAST(x.campaign_id AS STRING) AS id_campanha,
    x.campaign_name,
    x.campaign_status,
    CAST(x.ad_group_id AS STRING) AS id_grupo_anuncio,
    x.ad_group_name AS grupo_anuncio,
    x.search_term AS termo,
    x.search_term_match_type AS tipo_correspondencia,
    x.search_term_status AS status_termo,
    x.date,
    x.metrics_cost_micros,
    x.metrics_impressions,
    x.metrics_clicks,
    x.metrics_interactions,
    x.metrics_conversions,
    x.metrics_all_conversions,
    x.metrics_conversions_value,
    x.metrics_all_conversions_value,
    x.metrics_view_through_conversions,
    x.metrics_cross_device_conversions,
    TO_HEX(MD5(TO_JSON_STRING(x))) AS _payload_hash
  FROM `vanguardamartech_pmz_escola_de_mecanicos`.`google_ads_pmz_escola_mecanicossearch_term_performance` x
)
SELECT
  u.id_conta,
  u.id_campanha,
  NULLIF(TRIM(u.campaign_name), '')          AS campanha,
  u.campaign_status                          AS status_campanha,
  u.id_grupo_anuncio,
  u.grupo_anuncio,
  u.termo,
  u.tipo_correspondencia,
  u.status_termo,
  DATE(u.date)                               AS data,
  DATE_TRUNC(DATE(u.date), MONTH)            AS mes_referencia,

  u.metrics_cost_micros                      AS investimento_micros,
  u.metrics_impressions                      AS impressoes,
  u.metrics_clicks                           AS cliques,
  u.metrics_interactions                     AS interacoes,
  u.metrics_conversions                      AS conversoes,
  u.metrics_all_conversions                  AS todas_conversoes,
  u.metrics_conversions_value                AS valor_conversoes,
  u.metrics_all_conversions_value            AS valor_todas_conversoes,
  u.metrics_view_through_conversions         AS conversoes_view_through,
  u.metrics_cross_device_conversions         AS conversoes_entre_dispositivos,
  ROUND(u.metrics_cost_micros / 1000000, 2)  AS investimento,

  CURRENT_TIMESTAMP()                        AS _extraido_at,
  u._fonte,
  u._payload_hash
FROM uniao u
