"""Registro central dos modelos — importar daqui garante o mapeamento completo."""

from app.db.base import Base
from app.models.governance import (
    BudgetRule,
    CurationItem,
    Evaluation,
    EvaluationCase,
    EvaluationRun,
    PrivacyPolicy,
    ReviewDecision,
)
from app.models.lifecycle import (
    Deployment,
    DeploymentStatus,
    Environment,
    PortabilityJob,
    ServiceVersion,
    VersionStatus,
)
from app.models.runtime import (
    Conversation,
    ConversationStatus,
    Message,
    Span,
    SpanKind,
    TaskRun,
    TaskStatus,
    Trace,
)
from app.models.studio import (
    Agent,
    AgentSkill,
    AgentTool,
    AutonomyLevel,
    Channel,
    Integration,
    KnowledgeBase,
    KnowledgeDocument,
    LLMModel,
    LLMProvider,
    Service,
    ServiceAgent,
    ServiceStage,
    ServiceStatus,
    ServiceType,
    Skill,
    Tool,
)
from app.models.tenancy import (
    ApiKey,
    AuditLog,
    FeatureFlag,
    Permission,
    Role,
    RolePermission,
    Tenant,
    Unit,
    User,
    UserRole,
)

__all__ = [
    "Base",
    # tenancy
    "Tenant",
    "Unit",
    "User",
    "UserRole",
    "Role",
    "RolePermission",
    "Permission",
    "ApiKey",
    "FeatureFlag",
    "AuditLog",
    # studio
    "Service",
    "ServiceType",
    "ServiceStatus",
    "ServiceAgent",
    "ServiceStage",
    "Agent",
    "AgentTool",
    "AgentSkill",
    "AutonomyLevel",
    "Channel",
    "Skill",
    "Tool",
    "Integration",
    "KnowledgeBase",
    "KnowledgeDocument",
    "LLMProvider",
    "LLMModel",
    # lifecycle
    "ServiceVersion",
    "VersionStatus",
    "Deployment",
    "DeploymentStatus",
    "Environment",
    "PortabilityJob",
    # runtime
    "Conversation",
    "ConversationStatus",
    "Message",
    "TaskRun",
    "TaskStatus",
    "Trace",
    "Span",
    "SpanKind",
    # governance
    "CurationItem",
    "ReviewDecision",
    "Evaluation",
    "EvaluationCase",
    "EvaluationRun",
    "PrivacyPolicy",
    "BudgetRule",
]
