"""adiciona trechos de conhecimento

Revision ID: d344a878ad23
Revises: 509a2508674e
Create Date: 2026-08-27 13:11:44.015244+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# `sa.func.now()` compila por dialeto (now() no Postgres, CURRENT_TIMESTAMP no
# SQLite); nao fixe a sintaxe de um banco aqui.

revision: str = 'd344a878ad23'
down_revision: str | None = '509a2508674e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('base_uid', sa.String(length=36), nullable=False),
    sa.Column('document_uid', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedder', sa.String(length=32), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding_json', sa.JSON(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['base_uid'], ['knowledge_bases.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_uid'], ['knowledge_documents.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('document_uid', 'ordinal', name='uq_chunk_document_ordinal')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_base_uid'), ['base_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_uid'), ['document_uid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_uid'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_base_uid'))

    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
