"""adiciona acoes pendentes de aprovacao

Revision ID: 47a5bedd66ce
Revises: d344a878ad23
Create Date: 2026-08-27 13:35:13.045846+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# `sa.func.now()` compila por dialeto (now() no Postgres, CURRENT_TIMESTAMP no
# SQLite); nao fixe a sintaxe de um banco aqui.

revision: str = '47a5bedd66ce'
down_revision: str | None = 'd344a878ad23'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_actions',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('service_uid', sa.String(length=36), nullable=False),
    sa.Column('agent_uid', sa.String(length=36), nullable=True),
    sa.Column('tool_uid', sa.String(length=36), nullable=True),
    sa.Column('tool_name', sa.String(length=160), nullable=False),
    sa.Column('conversation_uid', sa.String(length=36), nullable=True),
    sa.Column('task_run_uid', sa.String(length=36), nullable=True),
    sa.Column('trace_uid', sa.String(length=36), nullable=True),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'executed', 'expired', name='actionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=160), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['service_uid'], ['services.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_actions_conversation_uid'), ['conversation_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_actions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_actions_task_run_uid'), ['task_run_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_actions_tenant_uid'), ['tenant_uid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_actions_tenant_uid'))
        batch_op.drop_index(batch_op.f('ix_pending_actions_task_run_uid'))
        batch_op.drop_index(batch_op.f('ix_pending_actions_status'))
        batch_op.drop_index(batch_op.f('ix_pending_actions_conversation_uid'))

    op.drop_table('pending_actions')
    # ### end Alembic commands ###
