"""baseline do schema

Revision ID: 509a2508674e
Revises: 
Create Date: 2026-08-27 13:07:39.375159+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# `sa.func.now()` compila por dialeto (now() no Postgres, CURRENT_TIMESTAMP no
# SQLite); nao fixe a sintaxe de um banco aqui.

revision: str = '509a2508674e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('resource', sa.String(length=48), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('tenants',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('document', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    op.create_table('api_keys',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)

    op.create_table('audit_logs',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('actor_email', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=False),
    sa.Column('resource_uid', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_email'), ['actor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_uid'), ['resource_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_uid'), ['tenant_uid'], unique=False)

    op.create_table('budget_rules',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('scope_uid', sa.String(length=36), nullable=True),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('limit_usd', sa.Float(), nullable=False),
    sa.Column('alert_at_percent', sa.Integer(), nullable=False),
    sa.Column('hard_stop', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('feature_flags',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('tenant_uid', 'code', name='uq_flag_tenant_code')
    )
    op.create_table('integrations',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('system', sa.String(length=96), nullable=False),
    sa.Column('auth_type', sa.String(length=48), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('credential_ref', sa.String(length=160), nullable=True),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_slug'), ['slug'], unique=False)

    op.create_table('knowledge_bases',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.String(length=96), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('data_classification', sa.String(length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_bases_name'), ['name'], unique=False)

    op.create_table('llm_providers',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('credential_ref', sa.String(length=160), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('llm_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_providers_code'), ['code'], unique=False)

    op.create_table('portability_jobs',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('artifact_uri', sa.String(length=500), nullable=True),
    sa.Column('checksum', sa.String(length=96), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('privacy_policies',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('data_category', sa.String(length=64), nullable=False),
    sa.Column('legal_basis', sa.String(length=96), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('redact_pii', sa.Boolean(), nullable=False),
    sa.Column('allow_provider_training', sa.Boolean(), nullable=False),
    sa.Column('storage_region', sa.String(length=48), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('roles',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('tenant_uid', 'code', name='uq_role_tenant_code')
    )
    op.create_table('skills',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('input_schema_json', sa.JSON(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_slug'), ['slug'], unique=False)

    op.create_table('tools',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_slug'), ['slug'], unique=False)

    op.create_table('units',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('cost_center', sa.String(length=64), nullable=True),
    sa.Column('monthly_budget_brl', sa.Float(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('tenant_uid', 'code', name='uq_unit_tenant_code')
    )
    op.create_table('knowledge_documents',
    sa.Column('base_uid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_uri', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=96), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['base_uid'], ['knowledge_bases.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('llm_models',
    sa.Column('provider_uid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('input_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('output_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['provider_uid'], ['llm_providers.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('llm_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_models_code'), ['code'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_uid', sa.String(length=36), nullable=False),
    sa.Column('permission_uid', sa.String(length=36), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_uid'], ['permissions.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_uid'], ['roles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('role_uid', 'permission_uid', name='uq_role_permission')
    )
    op.create_table('services',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('unit_uid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('conversation', 'task', 'copilot', name='servicetype', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'inactive', 'archived', name='servicestatus', native_enum=False, length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('objectives_json', sa.JSON(), nullable=False),
    sa.Column('channels_json', sa.JSON(), nullable=False),
    sa.Column('owner_email', sa.String(length=160), nullable=True),
    sa.Column('active_version', sa.String(length=32), nullable=True),
    sa.Column('has_draft', sa.Boolean(), nullable=False),
    sa.Column('handoff_enabled', sa.Boolean(), nullable=False),
    sa.Column('data_classification', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_uid'], ['units.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_type'), ['type'], unique=False)

    op.create_table('users',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('unit_uid', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_uid'], ['units.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('tenant_uid', 'email', name='uq_user_tenant_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('agents',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('model_uid', sa.String(length=36), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('autonomy', sa.Enum('n0_sugere', 'n1_executa_com_aprovacao', 'n2_executa_reversivel', 'n3_executa_irreversivel', name='autonomylevel', native_enum=False, length=32), nullable=False),
    sa.Column('owner_email', sa.String(length=160), nullable=True),
    sa.Column('knowledge_base_uid', sa.String(length=36), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_uid'], ['knowledge_bases.uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_uid'], ['llm_models.uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_slug'), ['slug'], unique=False)

    op.create_table('conversations',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('service_uid', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=160), nullable=True),
    sa.Column('channel', sa.Enum('webchat', 'whatsapp', 'voice', 'email', 'api', 'portal', name='channel', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('active', 'waiting', 'handoff', 'closed', 'failed', name='conversationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message', sa.Text(), nullable=False),
    sa.Column('handoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handoff_reason', sa.String(length=255), nullable=True),
    sa.Column('intent', sa.String(length=120), nullable=True),
    sa.Column('csat', sa.Integer(), nullable=True),
    sa.Column('is_recurrent', sa.Boolean(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['service_uid'], ['services.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_intent'), ['intent'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_public_id'), ['public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_service_uid'), ['service_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_tenant_uid'), ['tenant_uid'], unique=False)

    op.create_table('curation_items',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('service_uid', sa.String(length=36), nullable=False),
    sa.Column('trace_uid', sa.String(length=36), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('decision', sa.Enum('pending', 'approved', 'rejected', 'needs_revision', name='reviewdecision', native_enum=False, length=20), nullable=False),
    sa.Column('reviewer_email', sa.String(length=160), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['service_uid'], ['services.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('curation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curation_items_tenant_uid'), ['tenant_uid'], unique=False)

    op.create_table('evaluations',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('service_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('is_gate', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['service_uid'], ['services.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('service_stages',
    sa.Column('service_uid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('exit_condition', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['service_uid'], ['services.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('service_versions',
    sa.Column('service_uid', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'published', 'rolled_back', 'terminated', name='versionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=160), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['service_uid'], ['services.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('service_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_versions_service_uid'), ['service_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_versions_version'), ['version'], unique=False)

    op.create_table('task_runs',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('service_uid', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=48), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'awaiting_approval', 'cancelled', name='taskstatus', native_enum=False, length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('steps_total', sa.Integer(), nullable=False),
    sa.Column('steps_done', sa.Integer(), nullable=False),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['service_uid'], ['services.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_runs_public_id'), ['public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_runs_service_uid'), ['service_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_runs_tenant_uid'), ['tenant_uid'], unique=False)

    op.create_table('traces',
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('service_uid', sa.String(length=36), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('conversation_uid', sa.String(length=36), nullable=True),
    sa.Column('task_run_uid', sa.String(length=36), nullable=True),
    sa.Column('reference_label', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=96), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('tokens_reasoning', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['service_uid'], ['services.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_uid'], ['tenants.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traces_conversation_uid'), ['conversation_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_service_uid'), ['service_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_task_run_uid'), ['task_run_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_tenant_uid'), ['tenant_uid'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_uid', sa.String(length=36), nullable=False),
    sa.Column('role_uid', sa.String(length=36), nullable=False),
    sa.Column('granted_by', sa.String(length=160), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['role_uid'], ['roles.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('user_uid', 'role_uid', name='uq_user_role')
    )
    op.create_table('agent_skills',
    sa.Column('agent_uid', sa.String(length=36), nullable=False),
    sa.Column('skill_uid', sa.String(length=36), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_uid'], ['agents.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_uid'], ['skills.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('agent_tools',
    sa.Column('agent_uid', sa.String(length=36), nullable=False),
    sa.Column('tool_uid', sa.String(length=36), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_uid'], ['agents.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_uid'], ['tools.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('deployments',
    sa.Column('version_uid', sa.String(length=36), nullable=False),
    sa.Column('environment', sa.Enum('development', 'staging', 'production', name='environment', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'rolled_back', name='deploymentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=160), nullable=True),
    sa.Column('approved_by', sa.String(length=160), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_of_uid', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['version_uid'], ['service_versions.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_version_uid'), ['version_uid'], unique=False)

    op.create_table('evaluation_cases',
    sa.Column('evaluation_uid', sa.String(length=36), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_uid'], ['evaluations.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('evaluation_runs',
    sa.Column('evaluation_uid', sa.String(length=36), nullable=False),
    sa.Column('version_uid', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('passed_cases', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_uid'], ['evaluations.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_runs_evaluation_uid'), ['evaluation_uid'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_uid', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_uid'], ['conversations.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_uid'), ['conversation_uid'], unique=False)

    op.create_table('service_agents',
    sa.Column('service_uid', sa.String(length=36), nullable=False),
    sa.Column('agent_uid', sa.String(length=36), nullable=False),
    sa.Column('is_supervisor', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_uid'], ['agents.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_uid'], ['services.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('spans',
    sa.Column('trace_uid', sa.String(length=36), nullable=False),
    sa.Column('parent_uid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('chain', 'model', 'tool', 'skill', 'retrieval', 'guardrail', 'handoff', name='spankind', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['trace_uid'], ['traces.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spans_parent_uid'), ['parent_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_trace_uid'), ['trace_uid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spans_trace_uid'))
        batch_op.drop_index(batch_op.f('ix_spans_parent_uid'))

    op.drop_table('spans')
    op.drop_table('service_agents')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_uid'))

    op.drop_table('messages')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_evaluation_uid'))

    op.drop_table('evaluation_runs')
    op.drop_table('evaluation_cases')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_version_uid'))
        batch_op.drop_index(batch_op.f('ix_deployments_environment'))

    op.drop_table('deployments')
    op.drop_table('agent_tools')
    op.drop_table('agent_skills')
    op.drop_table('user_roles')
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traces_tenant_uid'))
        batch_op.drop_index(batch_op.f('ix_traces_task_run_uid'))
        batch_op.drop_index(batch_op.f('ix_traces_status'))
        batch_op.drop_index(batch_op.f('ix_traces_started_at'))
        batch_op.drop_index(batch_op.f('ix_traces_service_uid'))
        batch_op.drop_index(batch_op.f('ix_traces_conversation_uid'))

    op.drop_table('traces')
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_runs_tenant_uid'))
        batch_op.drop_index(batch_op.f('ix_task_runs_status'))
        batch_op.drop_index(batch_op.f('ix_task_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_task_runs_service_uid'))
        batch_op.drop_index(batch_op.f('ix_task_runs_public_id'))

    op.drop_table('task_runs')
    with op.batch_alter_table('service_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_versions_version'))
        batch_op.drop_index(batch_op.f('ix_service_versions_service_uid'))

    op.drop_table('service_versions')
    op.drop_table('service_stages')
    op.drop_table('evaluations')
    with op.batch_alter_table('curation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curation_items_tenant_uid'))

    op.drop_table('curation_items')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_tenant_uid'))
        batch_op.drop_index(batch_op.f('ix_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_conversations_started_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_service_uid'))
        batch_op.drop_index(batch_op.f('ix_conversations_public_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_intent'))

    op.drop_table('conversations')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_slug'))
        batch_op.drop_index(batch_op.f('ix_agents_name'))

    op.drop_table('agents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_type'))
        batch_op.drop_index(batch_op.f('ix_services_status'))
        batch_op.drop_index(batch_op.f('ix_services_slug'))
        batch_op.drop_index(batch_op.f('ix_services_name'))

    op.drop_table('services')
    op.drop_table('role_permissions')
    with op.batch_alter_table('llm_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_models_code'))

    op.drop_table('llm_models')
    op.drop_table('knowledge_documents')
    op.drop_table('units')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_slug'))
        batch_op.drop_index(batch_op.f('ix_tools_name'))

    op.drop_table('tools')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_slug'))
        batch_op.drop_index(batch_op.f('ix_skills_name'))

    op.drop_table('skills')
    op.drop_table('roles')
    op.drop_table('privacy_policies')
    op.drop_table('portability_jobs')
    with op.batch_alter_table('llm_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_providers_code'))

    op.drop_table('llm_providers')
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_name'))

    op.drop_table('knowledge_bases')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_slug'))
        batch_op.drop_index(batch_op.f('ix_integrations_name'))

    op.drop_table('integrations')
    op.drop_table('feature_flags')
    op.drop_table('budget_rules')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_uid'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_uid'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_email'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))

    op.drop_table('api_keys')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))

    op.drop_table('tenants')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    # ### end Alembic commands ###
